#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Script To Manage Brightness For Archcraft (in Wayland).

iDIR="$HOME/.config/hypr/mako/icons"

# Get brightness
get_backlight() {
	LIGHT=$(ddcutil --bus 5 --noverify --skip-ddc-checks getvcp 10 | grep -oP 'current value =\s+\K\d+')
	# LIGHT=$(printf "%.0f\n" `light -G`)
	echo "${LIGHT}"
}

# Get icons
get_icon() {
	backlight="$(get_backlight)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR"/brightness-20.png
	elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
		icon="$iDIR"/brightness-40.png
	elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
		icon="$iDIR"/brightness-60.png
	elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
		icon="$iDIR"/brightness-80.png
	elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
		icon="$iDIR"/brightness-100.png
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify-backlight -u low -i "$icon" "Brightness : $(get_backlight)"
}

# Increase brightness
inc_backlight() {
	# light -A 5 && get_icon 
	ddcutil --bus 5 --noverify --skip-ddc-checks setvcp 10 $(( 5 + $(get_backlight))) && get_icon 
}

# Decrease brightness
dec_backlight() {
	# light -U 5 && get_icon 
	ddcutil --bus 5 --noverify --skip-ddc-checks setvcp 10 $(( $(get_backlight) - 5 )) && get_icon 
}

# set brightness
set_backlight() {
	# light -U 5 && get_icon 
	ddcutil --bus 5 --noverify --skip-ddc-checks setvcp 10 $1 && get_icon 
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
elif [[ "$1" == "--set" || "$1" == "-s" ]]; then
	set_backlight $2
else
	get_backlight
fi
