#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

MIKU="$HOME/.config/hypr/wallpapers/miku.png"
NMIXX="$HOME/.config/hypr/wallpapers/nmixx.png"

swaybg --output 'HDMI-A-1' --mode fill --image "$MIKU" &
swaybg --output 'DP-3' --mode fill --image "$NMIXX" &
