hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, spring = "easy", style = "popin 0%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, spring = "easy", style = "popin" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, spring = "easy", style = "slide" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 20, bezier = "default" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 20, bezier = "default", style = "once" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 5, bezier = "default", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 5, bezier = "default", style = "slide" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 5, bezier = "default", style = "fade" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 5, bezier = "default", style = "fade" })
