hl.on("hyprland.start", function()
	hl.exec_cmd("hyprpm reload -n")
	hl.exec_cmd("kdeconnect-indicator")
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("clipse --listen")
	hl.exec_cmd("feishin")
	hl.exec_cmd("spotify")
	hl.exec_cmd("thunderbird")
	-- hl.exec_cmd("gtk-launch Gemini")
	hl.exec_cmd("tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE $HYPRLAND_INSTANCE_SIGNATURE")
	-- hl.exec_cmd("wlsunset -t 4500 -T 4501 -g 0.9")
	hl.exec_cmd("udiskie -a")
	hl.exec_cmd("hyprctl dispatch workspace 1")
	hl.exec_cmd("~/.config/hypr/scripts/startup")
end)
