#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


$HOME/.config/polybar/launch.sh --encoding=utf-8

feh --bg-center ~/dotfiles/wall.png --bg-fill

dunst -config ~/.config/dunst/dunstrc &

killall picom
picom --config ~/.config/picom.conf &

polybar 2>&1 /tmp/polybar.log &
