#!/usr/bin/env bash
#
#   ██████╗ ██████╗ ██╗ ██████╗ ██╗  ██╗████████╗███╗   ██╗███████╗███████╗███████╗
#   ██╔══██╗██╔══██╗██║██╔════╝ ██║  ██║╚══██╔══╝████╗  ██║██╔════╝██╔════╝██╔════╝	Author - rxyhn
#   ██████╔╝██████╔╝██║██║  ███╗███████║   ██║   ██╔██╗ ██║█████╗  ███████╗███████╗
#   ██╔══██╗██╔══██╗██║██║   ██║██╔══██║   ██║   ██║╚██╗██║██╔══╝  ╚════██║╚════██║	GitHub - https://github.com/rxyhn/tokyo
#   ██████╔╝██║  ██║██║╚██████╔╝██║  ██║   ██║   ██║ ╚████║███████╗███████║███████║
#   ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝╚══════╝╚══════╝
#

STEPS=1

function send_notification {
	icon="brightness.svg"
	brightness=$(brillo)
	dunstify -i $icon -t 1000 -r 2593 -u normal "Brightness $brightness%"
}


case $1 in
	up)
		brillo -q -A $STEPS
		send_notification
		;;
	down)
		brillo -q -U $STEPS
		send_notification
		;;
esac
