#!/usr/bin/env bash
#
#   ██████╗ ██████╗ ██╗ ██████╗ ██╗  ██╗████████╗███╗   ██╗███████╗███████╗███████╗
#   ██╔══██╗██╔══██╗██║██╔════╝ ██║  ██║╚══██╔══╝████╗  ██║██╔════╝██╔════╝██╔════╝	Author - rxyhn
#   ██████╔╝██████╔╝██║██║  ███╗███████║   ██║   ██╔██╗ ██║█████╗  ███████╗███████╗
#   ██╔══██╗██╔══██╗██║██║   ██║██╔══██║   ██║   ██║╚██╗██║██╔══╝  ╚════██║╚════██║	GitHub - https://github.com/rxyhn/tokyo
#   ██████╔╝██║  ██║██║╚██████╔╝██║  ██║   ██║   ██║ ╚████║███████╗███████║███████║
#   ╚═════╝ ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝╚══════╝╚══════╝╚══════╝
#

STEPS=5

function get_brightness {
	curr=$(brightnessctl g)
	max=$(brightnessctl m)
	echo $((curr * 100 / max))

}

function send_notification {
	icon="./brightness.svg"
	brightness=$(get_brightness)
	dunstify "Brightness $brightness%" --i $icon -r 5555 -u normal
}

case $1 in
	up)
		brightnessctl s +$STEPS%
		send_notification
		;;
	down)
		brightnessctl s $STEPS%-
		send_notification
		;;
esac
